### ISSUE TITLE
no screen in the rfctf pentoo container.

### ISSUE THREAD

**Issue by elkentaro** [rfhs/rfctf-container#8]
The Pentoo container doesn't have screen installed. sad panda.
<img width="260" alt="Screen Shot 2022-01-14 at 12 30 55" src="https://user-images.githubusercontent.com/7322588/149447837-8fb601ce-b601-4f66-8636-de5d43ed20f9.png">

**Comment by ZeroChaos-** [comment]
Fixed in the builds, it will be available in the next ctf.  Thanks for the report!
